name: fsi

x-logging:
  &limit-log
  options:
    # limit the combined log lines per container to 2MB
    max-size: "2000k"
  driver: json-file

services:

  fsi-server-24:
    image: ${FSI_SERVER_IMAGE_NAME}:${FSI_SERVER_IMAGE_TAG}
    restart: always
    container_name: fsi-server-24
    environment:
      - SOLR_SERVER_URI=${SOLR_SERVER_URI}
      - LOG_FSI_LEVEL=${LOG_FSI_LEVEL}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - ${FSI_CONFIG_PATH}:/srv/fsi/mounts/config
      - ${ASSET_PATH}:/srv/fsi/mounts/assets
      - ${OVERLAY_PATH}:/srv/fsi/mounts/overlay
      - ${STORAGE_PATH}:/srv/fsi/mounts/storage
      - ${LOG_PATH}/fsi:/srv/fsi/mounts/catalina/logs
    depends_on:
      solr-9:
        condition: service_started
        required: false
    logging: *limit-log
    deploy:
      resources:
        limits:
          memory: ${FSI_MEM_LIMIT}
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000

  solr-9:
    image: solr:9-slim
    restart: always
    container_name: solr-9
    profiles: [search]
    environment:
      - JAVA_TOOL_OPTIONS=-XX:MaxRAMPercentage=75.0
    command: ["/opt/solr/bin/solr", "start", "-p", "8983", "-f", "-force"]
    volumes:
      - ${SOLR_PATH}:/var/solr/data/fsi-server
    logging: *limit-log
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 1G
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8983/solr/admin/info/system || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s

  caddy:
    image: caddy:2-alpine
    container_name: caddy
    profiles: [proxy]
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    environment:
      - SERVER_DOMAINS=${SERVER_DOMAINS}
    volumes:
      - ./conf/caddy:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      fsi-server-24:
        condition: service_started
    logging: *limit-log

  lsyncd:
    build: builder/lsyncd
    profiles: [mirror]
    restart: always
    container_name: lsyncd
    env_file:
      - .env
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - ./conf/lsyncd/lsyncd.conf.lua:/config/lsyncd.lua:ro
      - ${MIRROR_SYNC_KEY}:/sync.key:ro
      - ${ASSET_PATH}:${ASSET_PATH}:ro
      - ${OVERLAY_PATH}:${OVERLAY_PATH}:ro
      - ${STORAGE_PATH}:${STORAGE_PATH}:ro
      - ${LOG_PATH}/lsync:/var/log
    # - ${FSI_CONFIG_PATH}:${FSI_CONFIG_PATH}:ro
    logging: *limit-log

volumes:
  caddy_data:
  caddy_config:
